name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '01 0 * * *'

jobs:
  build:
    runs-on: macOS-latest

    strategy:
        matrix:
          node-version: [10.x]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - uses: r-lib/actions/setup-r@v2
    
    - uses: r-lib/actions/setup-pandoc@v2
    
    - name: Update README
      run: |-
        Rscript -e "install.packages('rmarkdown')"
        Rscript -e "rmarkdown::render('README.Rmd')"
    - name: Commit and push if changed
      run: |-
        git add .
        git diff
        git config --global user.email "github-action-bot@example.com"
        git config --global user.name "GitHub Action Bot"
        git commit -m "Updated README" -a || echo "No changes to commit"
        git push
